import type { ChainId, ChainMeta } from "@/types/chain";

/**
 * The canonical registry of every chain MeneseSDK derives an address for.
 *
 * `sendSupported` reflects which chains Bridge.defi can currently sign &
 * broadcast for. The EVM family and Solana are fully wired; XRP and SUI use
 * their sign-only relayers. The remaining chains display addresses/balances
 * (receive + portfolio) and are ready to be enabled as their broadcasters
 * are added — see `src/lib/menese/send`.
 */
export const CHAINS: Record<ChainId, ChainMeta> = {
  ethereum: {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    decimals: 18,
    kind: "evm",
    evmChainId: 1,
    addressExplorer: "https://etherscan.io/address/",
    txExplorer: "https://etherscan.io/tx/",
    badge: "ET",
    accent: "text-[#627eea] bg-[#627eea]/10",
    coingeckoId: "ethereum",
    sendSupported: true,
  },
  arbitrum: {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ETH",
    decimals: 18,
    kind: "evm",
    evmChainId: 42161,
    addressExplorer: "https://arbiscan.io/address/",
    txExplorer: "https://arbiscan.io/tx/",
    badge: "AR",
    accent: "text-[#28a0f0] bg-[#28a0f0]/10",
    coingeckoId: "ethereum",
    sendSupported: true,
  },
  base: {
    id: "base",
    name: "Base",
    symbol: "ETH",
    decimals: 18,
    kind: "evm",
    evmChainId: 8453,
    addressExplorer: "https://basescan.org/address/",
    txExplorer: "https://basescan.org/tx/",
    badge: "BA",
    accent: "text-[#0052ff] bg-[#0052ff]/10",
    coingeckoId: "ethereum",
    sendSupported: true,
  },
  polygon: {
    id: "polygon",
    name: "Polygon",
    symbol: "POL",
    decimals: 18,
    kind: "evm",
    evmChainId: 137,
    addressExplorer: "https://polygonscan.com/address/",
    txExplorer: "https://polygonscan.com/tx/",
    badge: "PO",
    accent: "text-[#8247e5] bg-[#8247e5]/10",
    coingeckoId: "matic-network",
    sendSupported: true,
  },
  bsc: {
    id: "bsc",
    name: "BNB Chain",
    symbol: "BNB",
    decimals: 18,
    kind: "evm",
    evmChainId: 56,
    addressExplorer: "https://bscscan.com/address/",
    txExplorer: "https://bscscan.com/tx/",
    badge: "BN",
    accent: "text-[#f0b90b] bg-[#f0b90b]/10",
    coingeckoId: "binancecoin",
    sendSupported: true,
  },
  optimism: {
    id: "optimism",
    name: "Optimism",
    symbol: "ETH",
    decimals: 18,
    kind: "evm",
    evmChainId: 10,
    addressExplorer: "https://optimistic.etherscan.io/address/",
    txExplorer: "https://optimistic.etherscan.io/tx/",
    badge: "OP",
    accent: "text-[#ff0420] bg-[#ff0420]/10",
    coingeckoId: "ethereum",
    sendSupported: true,
  },
  solana: {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    decimals: 9,
    kind: "solana",
    addressExplorer: "https://solscan.io/account/",
    txExplorer: "https://solscan.io/tx/",
    badge: "SO",
    accent: "text-[#14f195] bg-[#14f195]/10",
    coingeckoId: "solana",
    sendSupported: true,
  },
  xrp: {
    id: "xrp",
    name: "XRP Ledger",
    symbol: "XRP",
    decimals: 6,
    kind: "xrp",
    addressExplorer: "https://xrpscan.com/account/",
    txExplorer: "https://xrpscan.com/tx/",
    badge: "XR",
    accent: "text-foreground bg-muted",
    coingeckoId: "ripple",
    sendSupported: true,
  },
  sui: {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    decimals: 9,
    kind: "sui",
    addressExplorer: "https://suiscan.xyz/mainnet/account/",
    txExplorer: "https://suiscan.xyz/mainnet/tx/",
    badge: "SU",
    accent: "text-[#4da2ff] bg-[#4da2ff]/10",
    coingeckoId: "sui",
    sendSupported: true,
  },
  bitcoin: {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    decimals: 8,
    kind: "bitcoin",
    addressExplorer: "https://mempool.space/address/",
    txExplorer: "https://mempool.space/tx/",
    badge: "BT",
    accent: "text-[#f7931a] bg-[#f7931a]/10",
    coingeckoId: "bitcoin",
    sendSupported: false,
  },
  litecoin: {
    id: "litecoin",
    name: "Litecoin",
    symbol: "LTC",
    decimals: 8,
    kind: "litecoin",
    addressExplorer: "https://blockchair.com/litecoin/address/",
    txExplorer: "https://blockchair.com/litecoin/transaction/",
    badge: "LT",
    accent: "text-[#345d9d] bg-[#345d9d]/10",
    coingeckoId: "litecoin",
    sendSupported: false,
  },
  ton: {
    id: "ton",
    name: "TON",
    symbol: "TON",
    decimals: 9,
    kind: "ton",
    addressExplorer: "https://tonscan.org/address/",
    txExplorer: "https://tonscan.org/tx/",
    badge: "TO",
    accent: "text-[#0098ea] bg-[#0098ea]/10",
    coingeckoId: "the-open-network",
    sendSupported: false,
  },
  cardano: {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    decimals: 6,
    kind: "cardano",
    addressExplorer: "https://cardanoscan.io/address/",
    txExplorer: "https://cardanoscan.io/transaction/",
    badge: "AD",
    accent: "text-[#0033ad] bg-[#0033ad]/10",
    coingeckoId: "cardano",
    sendSupported: false,
  },
  tron: {
    id: "tron",
    name: "Tron",
    symbol: "TRX",
    decimals: 6,
    kind: "tron",
    addressExplorer: "https://tronscan.org/#/address/",
    txExplorer: "https://tronscan.org/#/transaction/",
    badge: "TR",
    accent: "text-[#eb0029] bg-[#eb0029]/10",
    coingeckoId: "tron",
    sendSupported: false,
  },
  aptos: {
    id: "aptos",
    name: "Aptos",
    symbol: "APT",
    decimals: 8,
    kind: "aptos",
    addressExplorer: "https://explorer.aptoslabs.com/account/",
    txExplorer: "https://explorer.aptoslabs.com/txn/",
    badge: "AP",
    accent: "text-foreground bg-muted",
    coingeckoId: "aptos",
    sendSupported: false,
  },
  near: {
    id: "near",
    name: "NEAR",
    symbol: "NEAR",
    decimals: 24,
    kind: "near",
    addressExplorer: "https://nearblocks.io/address/",
    txExplorer: "https://nearblocks.io/txns/",
    badge: "NE",
    accent: "text-foreground bg-muted",
    coingeckoId: "near",
    sendSupported: false,
  },
  thorchain: {
    id: "thorchain",
    name: "THORChain",
    symbol: "RUNE",
    decimals: 8,
    kind: "thorchain",
    addressExplorer: "https://thorchain.net/address/",
    txExplorer: "https://thorchain.net/tx/",
    badge: "TH",
    accent: "text-[#23dcc8] bg-[#23dcc8]/10",
    coingeckoId: "thorchain",
    sendSupported: false,
  },
  icp: {
    id: "icp",
    name: "Internet Computer",
    symbol: "ICP",
    decimals: 8,
    kind: "icp",
    addressExplorer: "https://dashboard.internetcomputer.org/account/",
    txExplorer: "https://dashboard.internetcomputer.org/transaction/",
    badge: "IC",
    accent: "text-[#3b00b9] bg-[#3b00b9]/10",
    coingeckoId: "internet-computer",
    sendSupported: false,
  },
};

/** All chains in display order. */
export const CHAIN_LIST: ChainMeta[] = Object.values(CHAINS);

/** Chains Bridge.defi can send from (used by the Send page chain selector). */
export const SENDABLE_CHAINS: ChainMeta[] = CHAIN_LIST.filter(
  (c) => c.sendSupported,
);

/** The six configurable EVM chains backed by the RPC service. */
export const EVM_CHAINS: ChainMeta[] = CHAIN_LIST.filter(
  (c) => c.kind === "evm",
);

export function getChain(id: ChainId): ChainMeta {
  return CHAINS[id];
}

export function isEvmChain(id: ChainId): boolean {
  return CHAINS[id].kind === "evm";
}
